version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank_abc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: openjdk:17
    container_name: springboot_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_abc
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - ./app/target:/app
    working_dir: /app
    command: java -jar application.jar
    depends_on:
        - postgres

volumes:
  postgres_data:
